CXXFLAGS = -std=c++11 -Wall -Wextra -Wpedantic -fPIC
LDFLAGS = -shared -Wl,-soname,libTwoDimensionalMeasurement.so

TARGET = libTwoDimensionalMeasurement.so
SRC_FILES = TwoDimensionalMeasurement.cpp
OBJ_FILES = $(SRC_FILES:.cpp=.o)

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJ_FILES)
	$(CXX) $(LDFLAGS) $^ -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ_FILES) $(TARGET)